from dataclasses import dataclass

@dataclass
class Potion:
    name: str


POTIONS = ['Imp repellent',
           'Attack potion',
           'Antipoison',
           "Relicym's balm",
           'Strength potion',
           'Serum 207',
           'Guthix rest tea',
           'Compost potion',
           'Restore potion',
           'Guthix balance',
           'Blamish oil',
           'Energy potion',
           'Defence potion',
           'Agility potion',
           'Combat potion',
           'Prayer potion',
           'Super attack',
           'Goblin potion',
           'Superantipoison',
           'Fishing potion',
           'Super energy',
           'Shrink-me-quick',
           'Hunter potion',
           'Super strength',
           'Magic essence',
           'Weapon poison',
           'Super restore',
           'Sanfew serum',
           'Super defence',
           'Antidote+',
           'Antifire potion',
           'Divine super attack potion',
           'Divine super defence potion',
           'Divine super strength potion',
           'Ranging potion',
           'Weapon poison(+)',
           'Divine ranging potion',
           'Magic potion',
           'Stamina potion',
           'Zamorak brew',
           'Divine magic potion',
           'Antidote++',
           'Bastion potion',
           'Battlemage potion',
           'Saradomin brew',
           'Weapon poison(++)',
           'Extended antifire',
           'Ancient brew',
           'Divine bastion potion',
           'Divine battlemage potion',
           'Anti-venom',
           'Menaphite remedy',
           'Super combat potion',
           'Super antifire potion',
           'Anti-venom+',
           'Divine super combat potion',
           'Extended super antifire']

POTION_RECIPIES = [
    ['Attack potion', 'Guam leaf', 'Eye of Newt'],
    ['Antipoison', 'Marrentill', 'Unicorn horn dust'],
    ['Strength potion', 'Tarromin', 'Limpwurt root'],
    ['Serum 207', 'Tarromin', 'Ashes'],
    ['Guthix rest', 'Guam leaf(x2)', 'Marrentill', 'Harralander'],
    ['Compost potion', 'Harralander', 'Volcanic ash'],
    ['Restore potion', 'Harralander', 'Red spider eggs'],
    ['Energy potion', 'Harralander', 'Chocolate dust'],
    ['Defence potion', 'Ranarr weed', 'White berries'],
    ['Agility potion', 'Toadflax', "Toad's legs"],
    ['Combat potion', 'Harralander', 'Goat horn dust'],
    ['Prayer potion', 'Ranarr weed', 'Snape grass'],
    ['Super attack', 'Irit leaf', 'Eye of newt'],
    ['Superantipoison', 'Irit leaf', 'Unicorn horn dust'],
    ['Fishing potion', 'Avantoe', 'Snape grass'],
    ['Super energy', 'Avantoe', 'Mort myre fungus'],
    ['Hunter potion', 'Avantoe', 'Kebbit teeth dust'],
    ['Super strength', 'Kwuarm', 'Limpwurt root'],
    ['Weapon poison', 'Kwuarm', 'Dragon scale dust'],
    ['Super restore', 'Snapdragon', 'Red spider eggs'],
    ['Super defence', 'Cadantine', 'White berries'],
    ['Antidote+', 'Toadflax', 'Yew roots'],
    ['Antifire potion', 'Lantadyme', 'Dragon scale dust'],
    ['Ranging potion', 'Dwarf weed', 'Wine of zamorak'],
    ['Weapon poison(+)', 'Cactus spine', "Red spiders' eggs"],
    ['Magic potion', 'Lantadyme', 'Potato cactus'],
    ['Stamina potion', 'Super energy(4)', 'Amylase crystal(x4)'],
    ['Zamorak brew', 'Torstol', 'Jangerberries'],
    ['Antidote++', 'Irit leaf', 'Magic roots'],
    ['Bastion potion', 'Cadantine', 'Wine of zamorak'],
    ['Battlemage potion', 'Cadantine', 'Potato cactus'],
    ['Saradomin brew', 'Toadflax', 'Crushed nest'],
    ['Weapon poison(++)', 'Cave nightshade', 'Poison ivy berries'],
    ['Extended antifire', 'Antifire potion(4)', 'Lava scale shard(x4)'],
    ['Ancient brew', 'Dwarf weed', 'Nihil dust'],
    ['Anti-venom', 'Antidote++(4)', "Zulrah's scales(x20)"],
    ['Menaphite remedy', 'Dwarf weed', 'Lily of the sands'],
    ['Super combat potion', 'Super attack(4)', 'Torstol', 'Super strength(4)', 'Super defence(4)'],
    ['Anti-venom+', 'Anti-venom(4)', 'Torstol']
]